/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;
import BackEnd.Community;
import BackEnd.Encounter;
import BackEnd.EncounterHistory;
import FrontEnd.HospitalReg;
import FrontEnd.CommunityReg;
import BackEnd.HospitalRegisteration;
import BackEnd.HospitalRegisteration;
import BackEnd.JdbcConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patil
 */
public class PatientHomePage extends javax.swing.JFrame {

    /**
     * Creates new form PatientHomePage
     */
    public PatientHomePage() {
        initComponents();
    }
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
//    ArrayList<HospitalReg> hoslist = new ArrayList<>();
    ArrayList<Encounter> app = new ArrayList<>();
    ArrayList<HospitalRegisteration> hosreg = new ArrayList<>();
    HospitalReg hos = new HospitalReg();
    ArrayList<EncounterHistory> Ehis = new ArrayList<>();
    ArrayList<Community> com = new ArrayList<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ArrayList<HospitalRegisteration> getHospitalRegistrations(){
         String hos_name =  "Mayuri_hospital";
               String hos_id = "100";
               String community = "Mission Main";
               String hospital_address = "LMA";
               String doc_name = "doctor";
               String spec = "speciality";
               Long zip_code = 134568L;
               hosreg.add(new HospitalRegisteration(hos_name,zip_code ,hos_id,doc_name,community,hospital_address,spec));
        return hosreg;
    }
    
    
    

    
    
    
    
    public void encounter(String username, String password){
        
    try {
            JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
            pst = conn.prepareStatement("(SELECT patient_name,patient_id,city,symptoms,encounter_no,blood_pressure,heart_rate,tempreture,pulse,doctor_name,doctor_id,medication,diet,hospital,date_of_checkup from  vital_encountor_history where patient_id = (SELECT patient_id FROM PatientReg Where username = ? and password = ?));");
            pst.setString(1,username);
            pst.setString(2,password);
            rs = pst.executeQuery();
//            DefaultTableModel model = (DefaultTableModel) encountertable.getModel();
//            String ps = rs.getString(1);
//            System.out.println(ps);
            while(rs.next())
            {
               String patient_name =  rs.getString("patient_name");
               String patient_id = rs.getString("patient_id");
               String city = rs.getString("city");
               String symptoms = rs.getString("symptoms");
               int encounter_no = rs.getInt("encounter_no");
  
               int blood_pressure = rs.getInt("blood_pressure");
               Double heart_rate = rs.getDouble("heart_rate");
               Double tempreture = rs.getDouble("tempreture");
               int pulse = rs.getInt("pulse");
               String doctor_name = rs.getString("doctor_name");
               String doctor_id = rs.getString("doctor_id");
               String medication = rs.getString("medication");
               String diet = rs.getString("diet");
               String hospital = rs.getString("hospital");
               Date date_of_checkup = rs.getDate(15);
               
               Ehis.add(new EncounterHistory(patient_name,patient_id,city,symptoms,encounter_no,blood_pressure,heart_rate,tempreture,pulse,doctor_name,doctor_id,medication,diet,hospital,date_of_checkup));
               DefaultTableModel model = (DefaultTableModel) encountertable.getModel();
               
               model.addRow(new Object[] {patient_name,patient_id,city,symptoms,encounter_no,blood_pressure,heart_rate,tempreture,pulse,doctor_name,doctor_id,medication,diet,hospital,date_of_checkup});
          
            
            }
            
            
        
        } catch (SQLException ex) {
            Logger.getLogger(DoctorHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        encountertable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        area = new javax.swing.JComboBox<>();
        doctor1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        hospital = new javax.swing.JComboBox<>();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Welcome Patient");

        encountertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "patient_name", "patient_id", "city", "symptoms", "encounter_no", "blood_pressure", "heart_rate", "tempreture", "pulse", "doctor_name", "doctor_id", "medication", "diet", "hospital", "date_of_checkup"
            }
        ));
        encountertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encountertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(encountertable);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Hospital Finder in Community");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Enter City");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "Austin", "Las Vegas", "Seattle", "Denver" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Enter Area");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Hospital");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Doctor");

        area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                areaMousePressed(evt);
            }
        });
        area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaActionPerformed(evt);
            }
        });

        doctor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctor1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hospitalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hospitalMousePressed(evt);
            }
        });
        hospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Choose Date");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00", "10:20", "10:40", "11:00", "11:20", "11:40", "12:00", "12:20", "12:40", "13:00", "13:20", "13:40", "14:00" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBox1InputMethodTextChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Choose Time");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Patient_id");

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(112, 112, 112))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(hospital, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(area, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doctor1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(104, 104, 104))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encountertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encountertableMouseClicked
        // TODO add your handling code here:
        

        //        Level.setText(level);
        //        StartDate.setText(startdate);
        //        Ename.setText(name);
        //        Eid.setText(id);

    }//GEN-LAST:event_encountertableMouseClicked

   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            // TODO add your handling code here:
            JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
//            int age = Integer.parseInt(age1);
           
        try {
            pst = conn.prepareStatement("SELECT patient_id,doctor_name,appointment_date,appointment_time FROM appointment");
            rs = pst.executeQuery();
            while(rs.next())
            {
               String patient_id =  rs.getString("patient_id");
               String doctor_name = rs.getString("doctor_name");
               String appointment_date = rs.getString("appointment_date");
               String appointment_time = rs.getString("appointment_time");
               
               app.add(new Encounter(patient_id,doctor_name ,appointment_date,appointment_time));
               
              
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(PatientHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
            String Pid = jTextField1.getText();
            String Dname = doctor1.getSelectedItem().toString();
            Date app_date = jDateChooser3.getDate();
            String time = jComboBox1.getSelectedItem().toString();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            final String stringDate = dateFormat.format(app_date);
    //          for (int i = 0; i< app.size(); i++){
//               System.out.println(app.get(i).getAppointment_date());
//                if ((app.get(i).getAppointment_date().toString() == null ? (stringDate) == null : app.get(i).getAppointment_date().toString().equals(stringDate)) || (app.get(i).getAppointment_time() == null ? (time) == null : app.get(i).getAppointment_time().equals(time)))
//                    
//                  {
//
//                JOptionPane.showMessageDialog(this,
//                "This Appointment is booked by someone",
//                "Try again",
//                JOptionPane.ERROR_MESSAGE);
//                  break;
//                }
//                    
//                    
//                
//                else 
//                {
//                    app.add(new Encounter(Pname,Dname ,app_date,time));
            

            
                    try {
                    pst = conn.prepareStatement("INSERT INTO appointment(patient_id, doctor_name, appointment_date, appointment_time) values (?,?,?,?)");
                    pst.setString(1,Pid);
                    pst.setString(2,Dname);
                    pst.setString(3,stringDate);
                    pst.setString(4, time);
            
            
                int k = pst.executeUpdate();
                if (k==1){
                    JOptionPane.showMessageDialog(this, "Appoitment Booked Successfully !!!");
                        jTextField1.setText("");
                        doctor1.setSelectedItem(doctor1);
                    jDateChooser3.setDate(app_date);
                    jComboBox1.setSelectedItem("");
                    
                }
                else
                    {

                    JOptionPane.showMessageDialog(this,
                    "Error in booking appointment!",
                    "Try again",
                    JOptionPane.ERROR_MESSAGE);
                    
                    }


            } catch (SQLException ex) {
                Logger.getLogger(HospitalReg.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
                
                
            


                

                    
            
             
        
        
        
        
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
         JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
//            int age = Integer.parseInt(age1);
           
        try {
            pst = conn.prepareStatement("SELECT city,area,hospital,doctor FROM Community");
            rs = pst.executeQuery();
            while(rs.next())
            {
               String city =  rs.getString("city");
               String area = rs.getString("area");
               String hospital = rs.getString("hospital");
               String doctor = rs.getString("doctor");
               
               
               
               com.add(new Community(city,area,hospital,doctor));
              
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(PatientHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        String city = jComboBox2.getSelectedItem().toString();
        for (int i = 0;i< com.size();i++){
            if (com.get(i).getCity().equalsIgnoreCase(city)){
                area.addItem(com.get(i).getArea());
            }
        }
//        CommunityReg cr = new CommunityReg();
//        for (int i = 0; i < cr.Register().size();i++);
//        {
//        System.out.println(cr.Register().get(i));
//        }
        
//        String lo = "longwood";
//        area.addItem(lo);
      
//            int age = Integer.parseInt(age1);
           
//        try {
//            pst = conn.prepareStatement("SELECT area FROM community where city = ?");
//            pst.setString(1,city);
//            rs = pst.executeQuery();
//            while(rs.next())
//            {
//               String ar =  rs.getString("area");
//               System.out.println(ar);
//               area.addItem(ar);
//                
//            }
//        }catch (SQLException ex) {
//                Logger.getLogger(HospitalReg.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaActionPerformed
        // TODO add your handling code here:
      
      
        
        
        
    }//GEN-LAST:event_areaActionPerformed

    private void areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaMouseClicked
        // TODO add your handling code here:
    
      String a1 = area.getSelectedItem().toString();
//        String lo = "longwood";
//        area.addItem(lo);
        System.out.println(a1);
         JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
//            int age = Integer.parseInt(age1);
           
        try {
            pst = conn.prepareStatement("SELECT city,area,hospital,doctor FROM Community");
            rs = pst.executeQuery();
            while(rs.next())
            {
               String city =  rs.getString("city");
               String area = rs.getString("area");
               String hospital = rs.getString("hospital");
               String doctor = rs.getString("doctor");
               
               
               
               com.add(new Community(city,area,hospital,doctor));
              
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(PatientHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0;i< com.size();i++){
            if (com.get(i).getArea().equalsIgnoreCase(a1)){
                hospital.addItem(com.get(i).getHospital());
            }
        }
    }//GEN-LAST:event_areaMouseClicked

    
    
    
    private void hospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalActionPerformed
        // TODO add your handling code here:
        
            
      
    }//GEN-LAST:event_hospitalActionPerformed

    private void hospitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitalMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hospitalMousePressed

    private void hospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospitalMouseClicked
        // TODO add your handling code here:
        String hosp = hospital.getSelectedItem().toString();
        String area1 = area.getSelectedItem().toString();
//        String lo = "longwood";
//        area.addItem(lo);
        JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
//            int age = Integer.parseInt(age1);
           
        try {
            pst = conn.prepareStatement("SELECT city,area,hospital,doctor FROM Community");
            rs = pst.executeQuery();
            while(rs.next())
            {
               String city =  rs.getString("city");
               String area = rs.getString("area");
               String hospital = rs.getString("hospital");
               String doctor = rs.getString("doctor");
               
               
               
               com.add(new Community(city,area,hospital,doctor));
              
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(PatientHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0;i< com.size();i++){
            if (com.get(i).getHospital().equalsIgnoreCase(hosp) && com.get(i).getArea().equalsIgnoreCase(area1)){
                doctor1.addItem(com.get(i).getDoctor());
                System.out.println(com.get(i).getDoctor());
            }
        }
                           
    }//GEN-LAST:event_hospitalMouseClicked

    private void areaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_areaMousePressed

    private void doctor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctor1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        WeDoCare wdc = new WeDoCare();
        wdc.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBox1InputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1InputMethodTextChanged

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        JdbcConnection jdbc = new JdbcConnection();
            Connection conn = jdbc.Connect();
            
//            int age = Integer.parseInt(age1);
           
        try {
            pst = conn.prepareStatement("SELECT patient_id,doctor_name,appointment_date,appointment_time FROM appointment");
            rs = pst.executeQuery();
            while(rs.next())
            {
               String patient_id =  rs.getString("patient_id");
               String doctor_name = rs.getString("doctor_name");
               String appointment_date = rs.getString("appointment_date");
               String appointment_time = rs.getString("appointment_time");
               
               app.add(new Encounter(patient_id,doctor_name ,appointment_date,appointment_time));
               
              
                
            }
            } catch (SQLException ex) {
            Logger.getLogger(PatientHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
            String Pid = jTextField1.getText();
            String Dname = doctor1.getSelectedItem().toString();
            Date app_date = jDateChooser3.getDate();
            String time = jComboBox1.getSelectedItem().toString();
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            final String stringDate = dateFormat.format(app_date);
        
            for(int i =0; i < app.size();i++){
            if (app.get(i).getAppointment_date().equalsIgnoreCase(stringDate) && app.get(i).getAppointment_time().equalsIgnoreCase(time)){
                {

                    JOptionPane.showMessageDialog(this,
                    "This appointment is already booked",
                    "Please try to book another slot",
                    JOptionPane.ERROR_MESSAGE);
                    
                    }
            
            }
            } 
    }//GEN-LAST:event_jTextField1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> area;
    private javax.swing.JComboBox<String> doctor1;
    private javax.swing.JTable encountertable;
    private javax.swing.JComboBox<String> hospital;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
